version: "3.8"
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - docker-mysql
  docker-mysql:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root